// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TestMembership {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Login Login1;
		
		protected System.Web.UI.WebControls.CreateUserWizard CreateUserWizard1;
		
		protected System.Web.UI.WebControls.ChangePassword ChangePassword1;
		
		protected System.Web.UI.WebControls.PasswordRecovery PasswordRecovery1;
	}
}
